### ISSUE TITLE
Raspberry Pi 4B version

### ISSUE THREAD

**Issue by schneiderLukas** [niciBume/Cat_Prey_Analyzer#33]
Hello,

I just tried to make that thing running on my raspberry pi 4b, unfortunately I do get a lot of issues over and over and I came to the conclusion that there might be a problem with the versions of the packages and python itself. I just wondered if I could install older versions of them to make it running... With what versions did you run it?

Thank you and Merry Christmas

**Comment by niciBume** [comment]
Hi there

Yeah that should work out. This is the output of `pip list` for me:

```
Package               Version
--------------------- ---------
absl-py               0.9.0
asn1crypto            0.24.0
astor                 0.8.1
attrs                 19.3.0
backcall              0.1.0
bleach                3.1.1
cachetools            4.0.0
certifi               2018.8.24
chardet               3.0.4
colorzero             1.1
cryptography          2.6.1
cycler                0.10.0
Cython                0.29.15
decorator             4.4.1
defusedxml            0.6.0
entrypoints           0.3
future                0.18.2
gast                  0.2.2
google-auth           1.11.2
google-auth-oauthlib  0.4.1
google-pasta          0.1.8
gpiozero              1.5.1
grpcio                1.27.2
h5py                  2.9.0
idna                  2.6
importlib-metadata    1.5.0
ipykernel             5.1.4
ipython               7.12.0
ipython-genutils      0.2.0
ipywidgets            7.5.1
jedi                  0.16.0
Jinja2                2.11.1
jsonschema            3.2.0
jupyter               1.0.0
jupyter-client        6.0.0
jupyter-console       6.1.0
jupyter-core          4.6.3
Keras-Applications    1.0.8
Keras-Preprocessing   1.1.0
keyring               17.1.1
keyrings.alt          3.1.1
kiwisolver            1.1.0
lxml                  4.5.0
Markdown              3.2.1
MarkupSafe            1.1.1
matplotlib            3.1.3
mistune               0.8.4
mock                  4.0.1
nbconvert             5.6.1
nbformat              5.0.4
notebook              6.0.3
numpy                 1.16.2
oauthlib              3.1.0
opencv-contrib-python 4.1.0.25
opencv-python         4.1.1.26
opt-einsum            3.1.0
pandas                1.0.3
pandocfilters         1.4.2
parso                 0.6.2
pexpect               4.8.0
picamera              1.13
pickleshare           0.7.5
Pillow                7.0.0
pip                   20.2.4
prometheus-client     0.7.1
prompt-toolkit        3.0.3
protobuf              3.11.3
ptyprocess            0.6.0
pyasn1                0.4.8
pyasn1-modules        0.2.8
pybind11              2.5.0
pycrypto              2.6.1
Pygments              2.5.2
PyGObject             3.30.4
pyparsing             2.4.6
pyrsistent            0.15.7
python-apt            1.8.4.1
python-dateutil       2.8.1
python-telegram-bot   12.7
pytz                  2019.3
pyxdg                 0.25
pyzmq                 19.0.0
qtconsole             4.6.0
requests              2.21.0
requests-oauthlib     1.3.0
RPi.GPIO              0.7.0
rpimotorlib           3.1
rsa                   4.0
scipy                 1.4.1
SecretStorage         2.3.1
Send2Trash            1.5.0
setuptools            45.2.0
six                   1.14.0
ssh-import-id         5.7
telegram              0.0.1
tensorboard           2.0.2
tensorflow            1.14.0
tensorflow-estimator  1.14.0
termcolor             1.1.0
terminado             0.8.3
testpath              0.4.4
tornado               6.0.3
traitlets             4.3.3
urllib3               1.24.1
wcwidth               0.1.8
webencodings          0.5.1
Werkzeug              1.0.0
wheel                 0.34.2
widgetsnbextension    3.5.1
wrapt                 1.12.0
zipp                  3.0.0
```
Creatign a container for this project would be a good thing as well.

**Comment by schneiderLukas** [comment]
Hi,

thank you for you fast response.
I now tried a few hours to get that thing running on my machine as well as in an container.
I would be really thankful if you could help me.

I've got the problem that I need to build that image on the Raspberry itself as I need picamera which I can only install when building on the machine itself. Otherwise I am getting this error (trying to build it on windows):
```
35.80   Running setup.py install for picamera: started
35.95   Running setup.py install for picamera: finished with status 'error'
35.96   error: subprocess-exited-with-error
35.96
35.96   × Running setup.py install for picamera did not run successfully.
35.96   │ exit code: 1
35.96   ╰─> [19 lines of output]
35.96       running install
35.96       Traceback (most recent call last):
35.96         File "<string>", line 36, in <module>
35.96         File "<pip-setuptools-caller>", line 34, in <module>
35.96         File "/tmp/pip-install-58t2c1fl/picamera_2d75c2f46a8b4d4295f5617ecc671aa8/setup.py", line 145, in <module>
35.96           main()
35.96         File "/tmp/pip-install-58t2c1fl/picamera_2d75c2f46a8b4d4295f5617ecc671aa8/setup.py", line 140, in main
35.96           cmdclass             = {'install': CustomInstallCommand},
35.96         File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
35.96           return distutils.core.setup(**attrs)
35.96         File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
35.96           dist.run_commands()
35.96         File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
35.96           self.run_command(cmd)
35.96         File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
35.96           cmd_obj.run()
35.96         File "/tmp/pip-install-58t2c1fl/picamera_2d75c2f46a8b4d4295f5617ecc671aa8/setup.py", line 111, in run
35.96           raise ValueError('Unable to determine if this system is a Raspberry Pi')
35.96       ValueError: Unable to determine if this system is a Raspberry Pi
35.96       [end of output]
```

My Dockerfile looks like this:

```
# Use Python 3.7 slim base image compatible with ARM architecture
FROM python:3.7-slim-buster

# Set working directory in the container
WORKDIR /app

# Install system dependencies required for TensorFlow
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements file (if you have one)
COPY requirements.txt .

# Install TensorFlow and its models
# RUN pip install --no-cache-dir tensorflow @ https://files.pythonhosted.org/packages/f4/28/96efba1a516cdacc2e2d6d081f699c001d414cc8ca3250e6d59ae657eb2b/tensorflow-1.14.0-cp37-cp37m-manylinux1_x86_64.whl
# RUN git clone https://github.com/tensorflow/models.git tensorflow/models

# Detect if the system is a Raspberry Pi and install picamera only if true
RUN if [ -e /sys/firmware/devicetree/base/model ]; then \
    pip install picamera==1.13; \
    fi

RUN pip install --break-system-packages --no-cache-dir -r requirements.txt

# Add TensorFlow models to Python path using ENV (Docker's way)
ENV PYTHONPATH="${PYTHONPATH}:/app/tensorflow/models/research:/app/tensorflow/models/research/slim"

# Copy your project files
COPY . .

# Make the script executable
# COPY catCam_starter.sh .
# RUN chmod +x catCam_starter.sh

# Command to run your application
CMD ["python3", "cascade.py"]
```

And I am trying to get tensorflow 1.14 from this website:
[(https://files.pythonhosted.org/packages/f4/28/96efba1a516cdacc2e2d6d081f699c001d414cc8ca3250e6d59ae657eb2b/tensorflow-1.14.0-cp37-cp37m-manylinux1_x86_64.whl)]
as I am not able to install it via pip install tensorflow. Unfortunately this it not for arm64 so I am unable to install it, both in the container and locally, I couldn't find any other Version which could work to my knowledge.

Thank you!

**Comment by niciBume** [comment]
Following [xx](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi) from the readme you should be able to get the wheel from here: `wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.8.0/tensorflow-1.8.0-cp35-none-linux_armv7l.whl`

Yes you will need to build the container on the pi due to it being ARM.

**Comment by schneiderLukas** [comment]
I finally managed to to start up that thing in a container, now i wonder how to get the picamera running...
I created a docker image of tensorflow 1.14 with pyhton3.7 as base image in order to simplify the main dockerfile where all the code is inside. ChatGPT helped me a lot as i dont have that much experience in docker to be honest.
both dockerfiles are in the appendix. When i try to directly run `RUN pip install picamera`, it fails while building

[Dockerfile1.txt](https://github.com/user-attachments/files/18526602/Dockerfile1.txt)
[Dockerfile2.txt](https://github.com/user-attachments/files/18526601/Dockerfile2.txt)

[dockerbuild_log.txt](https://github.com/user-attachments/files/18526597/dockerbuild_log.txt)

this gives me this error when trying to run the container
`Traceback (most recent call last):

  File "cascade.py", line 16, in <module>

    from camera_class import Camera

  File "/app/camera_class.py", line 2, in <module>

    from picamera import Picamera

ModuleNotFoundError: No module named 'picamera'`


I really much appreciate your help, thank you

**Comment by schneiderLukas** [comment]
Hello again,

I think I just figured out the root of all the issues I faced trying to get it running on my raspberry pi 4b.
Until now I always got stuck on trying to get the picamera image running, I always got the error the libcam.so couldn't be found, so then I thought that the docker container might be the problem, so I tried to run it locally with Pyenv (Python 3.7.17) - just to find out that I face the same issue.
Now I found out that on the raspios version I used, the picamera package wont work, just the picamera2 package would , but then I found out that the picamera2 package must have python3.9 or higher... As Tensorflow1.14.0 is available just for python3.7 and some earlier versions, this is no possible solution to my problem. I then tried to install an earlier raspios image.
Now I installed raspios2023-05-03 (64bit) which is the oldest that runs on my raspberry and I changed the camera interface to legacy enable - even now I still face the same issue with the picamera package.

Maybe this would help in the future if anyone faces the same issues.

Tomorrow I will try the 32bit raspios to see if that will solve my problem. Regarding to this post [xx](https://www.reddit.com/r/raspberry_pi/comments/13p199l/issues_accessing_pi_camera_in_64bit_raspberry_pi/?rdt=42844) picamera just works on 32bit os.

Did you run this application on a 32bit os?

**Comment by niciBume** [comment]
Hi there, 

Thanks for the info! Yes my pi is 32 bit:

```
pi@raspberrypi:~ $ dpkg --print-architecture
armhf
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```

Good luck!
